[package]
name = "rigforge"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true

rigforge-ai = { path = "../../crates/rigforge-ai" }
rigforge-audio = { path = "../../crates/rigforge-audio" }
rigforge-core = { path = "../../crates/rigforge-core" }
rigforge-log = { path = "../../crates/rigforge-log" }
rigforge-radio = { path = "../../crates/rigforge-radio" }
rigforge-tui = { path = "../../crates/rigforge-tui" }
