[package]
name = "qsonaut-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ab_glyph = "0.2"
anyhow.workspace = true
async-trait = "0.1"
eframe.workspace = true
wgpu.workspace = true
tokio.workspace = true
tracing.workspace = true
rustfft.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
toml.workspace = true
hound = "3.5"
tempfile = "3"
base64.workspace = true
image.workspace = true
imageproc = "0.25"
egui-file-dialog = { version = "=0.12.0", default-features = false }

qsonaut-audio = { path = "../qsonaut-audio" }
qsonaut-accelerate = { path = "../qsonaut-accelerate" }
qsonaut-core = { path = "../qsonaut-core" }
qsonaut-hostbridge-client = { path = "../qsonaut-hostbridge-client" }
qsonaut-hostbridge-protocol = { git = "https://github.com/nicksbar/QSONaut-HostBridge.git", rev = "35aecc6" }
qsonaut-automation = { path = "../qsonaut-automation" }
qsonaut-log = { path = "../qsonaut-log" }
qsonaut-radio = { package = "rigwright", version = "0.1.19", path = "../../../rigwright" }
qsonaut-pskreporter = { path = "../qsonaut-pskreporter" }
qsonaut-server-client = { path = "../qsonaut-server-client" }
qsonaut-modems = { git = "https://github.com/nicksbar/qsonaut-modems.git", rev = "6cc26b8" }
qsonaut-third-party = { path = "../../../qsonaut-third-party/crates/qsonaut-third-party" }
