[package]
name = "qsonaut-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ab_glyph = "0.2"
anyhow.workspace = true
eframe.workspace = true
wgpu.workspace = true
tokio.workspace = true
tracing.workspace = true
rustfft.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
toml.workspace = true
mfsk-core = { git = "https://github.com/jl1nie/mfsk-core.git", rev = "5334e11176ac78fabda51ba2ec9d5bce359f3e83", default-features = false, features = ["full"] }
cwdit-dsp = { git = "https://github.com/swilcox/cw-dit.git", rev = "153fc247ce6e4934c94e0cd2dcbf7887e368ec29" }
cwdit-morse = { git = "https://github.com/swilcox/cw-dit.git", rev = "153fc247ce6e4934c94e0cd2dcbf7887e368ec29" }
hound = "3.5"
tempfile = "3"
base64.workspace = true
image.workspace = true
imageproc = "0.25"
egui-file-dialog = { version = "=0.12.0", default-features = false }

qsonaut-audio = { path = "../qsonaut-audio" }
qsonaut-accelerate = { path = "../qsonaut-accelerate" }
qsonaut-core = { path = "../qsonaut-core" }
qsonaut-automation = { path = "../qsonaut-automation" }
qsonaut-log = { path = "../qsonaut-log" }
qsonaut-radio = { package = "rigwright", version = "0.1.10" }
qsonaut-pskreporter = { path = "../qsonaut-pskreporter" }
qsonaut-server-client = { path = "../qsonaut-server-client" }
qsonaut-sstv = { path = "../qsonaut-sstv" }
