[package]
name = "qsonaut"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true

qsonaut-ai = { path = "../../crates/qsonaut-ai" }
qsonaut-audio = { path = "../../crates/qsonaut-audio" }
qsonaut-core = { path = "../../crates/qsonaut-core" }
qsonaut-log = { path = "../../crates/qsonaut-log" }
qsonaut-radio = { package = "rigwright", git = "https://github.com/nicksbar/rigwright" }
qsonaut-gui = { path = "../../crates/qsonaut-gui" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_UI_WindowsAndMessaging"] }

[build-dependencies]
image = { version = "0.25", default-features = false, features = ["ico", "png"] }
winresource = "0.1"
