[package]
name = "rigforge-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
eframe.workspace = true
tokio.workspace = true
tracing.workspace = true
rustfft.workspace = true

rigforge-audio = { path = "../rigforge-audio" }
rigforge-core = { path = "../rigforge-core" }
rigforge-radio = { path = "../rigforge-radio" }
