[package]
name = "rigforge-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
eframe.workspace = true
tokio.workspace = true
tracing.workspace = true
rustfft.workspace = true
serde.workspace = true
toml.workspace = true
mfsk-core = { path = "../../../mfsk-core/mfsk-core", default-features = false, features = ["full"] }

rigforge-audio = { path = "../rigforge-audio" }
rigforge-dsp   = { path = "../rigforge-dsp" }
rigforge-core = { path = "../rigforge-core" }
rigforge-log = { path = "../rigforge-log" }
rigforge-radio = { path = "../rigforge-radio" }
